backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: static/img
public_folder: /img
collections:
  - label: "Who we are"
    name: "whoweare"
    folder: "content/whoweare"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"} 
      - {label: "Category", name: "category", widget: "hidden", default: "whoweare"}

  - label: "Team Member"
    name: "team"
    folder: "content/team"
    create: true
    slug: "{{firstName}}-{{lastName}}"
    media_folder: "../../images/members"
    fields:
      - {label: "Member Image", name: "memberImg", widget: "image", choose_url: true}
      - {label: "First Name", name: "firstName", widget: "string"}
      - {label: "Last Name", name: "lastName", widget: "string"}
      - {label: "Designation", name: "designation", widget: "string"}
      - {label: "LinkedIn", name: "linikedIn", widget: "string"}
      - {label: "Active", name: "isActive", widget: "boolean"}
      - {label: "Company", name: "company", widget: "hidden", default: "Penthara"}

  - label: "Testimonial"
    name: "testimonials"
    folder: "content/testimonials"
    create: true
    slug: "{{name}}"
    media_folder: "../../images/clientsImg"
    fields:
      - {label: "Client Image", name: "client_image", widget: "image", choose_url: true}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Client Name", name: "name", widget: "string"}
      - {label: "Company", name: "client_company", widget: "string"}
      - {label: "Designation", name: "client_designation", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"} 
      - {label: "Category", name: "category", widget: "hidden", default: "testimonials"}
  
  - label: "Footer"
    name: "footer"
    folder: "content/footer"
    create: true
    slug: "{{name}}"
    media_folder: "../../images"
    fields:
      - {label: "India Location", name: "location_india", widget: "string"}
      - {label: "USA Location", name: "location_usa", widget: "string"}
      - {label: "Contact India", name: "contact_india", widget: "string"}
      - {label: "Contact USA", name: "contact_usa", widget: "string"}
      - {label: "FaceBook", name: "faceBook", widget: "string"} 
      - {label: "YouTube", name: "youTube", widget: "string"}
      - {label: "LinkedIn", name: "linkedin", widget: "string"}
      - {label: "Twitter", name: "twitter", widget: "string"}
      - {label: "Category", name: "category", widget: "hidden", default: "footer"}


